# Makefile generated by MakefileGenerator.cs
# *DO NOT EDIT*

UNREALROOTPATH = /home/ariel/UE
GAMEPROJECTFILE =/home/ariel/Documentos/Unreal Projects/SpaceShooterUnreal/SpaceShooter.uproject

TARGETS = \
	SpaceShooter-Linux-DebugGame  \
	SpaceShooter-Linux-Shipping  \
	SpaceShooter \
	SpaceShooterEditor-Linux-DebugGame  \
	SpaceShooterEditor-Linux-Shipping  \
	SpaceShooterEditor \
	UnrealEditor-Linux-DebugGame  \
	UnrealEditor-Linux-Shipping  \
	UnrealEditor \
	UnrealGame-Linux-DebugGame  \
	UnrealGame-Linux-Shipping  \
	UnrealGame\
	configure

BUILD = bash "$(UNREALROOTPATH)/Engine/Build/BatchFiles/Linux/Build.sh"
PROJECTBUILD = "$(UNREALROOTPATH)/Engine/Binaries/ThirdParty/DotNet/6.0.302/linux/dotnet" "$(UNREALROOTPATH)/Engine/Binaries/DotNET/UnrealBuildTool/UnrealBuildTool.dll"

all: StandardSet

RequiredTools: CrashReportClient-Linux-Shipping CrashReportClientEditor-Linux-Shipping ShaderCompileWorker UnrealLightmass EpicWebHelper-Linux-Shipping

StandardSet: RequiredTools UnrealFrontend SpaceShooterEditor UnrealInsights

DebugSet: RequiredTools UnrealFrontend-Linux-Debug SpaceShooterEditor-Linux-Debug


SpaceShooter-Linux-DebugGame:
	 $(PROJECTBUILD) SpaceShooter Linux DebugGame  -project="$(GAMEPROJECTFILE)" $(ARGS)

SpaceShooter-Linux-Shipping:
	 $(PROJECTBUILD) SpaceShooter Linux Shipping  -project="$(GAMEPROJECTFILE)" $(ARGS)

SpaceShooter:
	 $(PROJECTBUILD) SpaceShooter Linux Development  -project="$(GAMEPROJECTFILE)" $(ARGS)

SpaceShooterEditor-Linux-DebugGame:
	 $(PROJECTBUILD) SpaceShooterEditor Linux DebugGame  -project="$(GAMEPROJECTFILE)" $(ARGS)

SpaceShooterEditor-Linux-Shipping:
	 $(PROJECTBUILD) SpaceShooterEditor Linux Shipping  -project="$(GAMEPROJECTFILE)" $(ARGS)

SpaceShooterEditor:
	 $(PROJECTBUILD) SpaceShooterEditor Linux Development  -project="$(GAMEPROJECTFILE)" $(ARGS)

UnrealEditor-Linux-DebugGame:
	 $(BUILD) UnrealEditor Linux DebugGame  -project="$(GAMEPROJECTFILE)" $(ARGS)

UnrealEditor-Linux-Shipping:
	 $(BUILD) UnrealEditor Linux Shipping  -project="$(GAMEPROJECTFILE)" $(ARGS)

UnrealEditor:
	 $(BUILD) UnrealEditor Linux Development  -project="$(GAMEPROJECTFILE)" $(ARGS)

UnrealGame-Linux-DebugGame:
	 $(BUILD) UnrealGame Linux DebugGame  -project="$(GAMEPROJECTFILE)" $(ARGS)

UnrealGame-Linux-Shipping:
	 $(BUILD) UnrealGame Linux Shipping  -project="$(GAMEPROJECTFILE)" $(ARGS)

UnrealGame:
	 $(BUILD) UnrealGame Linux Development  -project="$(GAMEPROJECTFILE)" $(ARGS)

configure:
	xbuild /property:Configuration=Development /verbosity:quiet /nologo "$(UNREALROOTPATH)/Engine/Source/Programs/UnrealBuildTool/UnrealBuildTool.csproj"
	$(PROJECTBUILD) -projectfiles -project="\"$(GAMEPROJECTFILE)\"" -game -engine 

.PHONY: $(TARGETS)
